name: PureAuth
version: 4.0.2
main: com.pureauth.PureAuth
api-version: 1.21
authors: [SzymeX Dev Studio]
softdepend: [PlaceholderAPI]
commands:
  register:
    description: Register a new account
    usage: /register <password> <password> [captcha]
  login:
    description: Login to your account
    usage: /login <password>
  changepass:
    description: Change your password
    usage: /changepass <old> <new> <new>
  premium:
    description: Enable Premium Auto-Login (IP-Based)
    usage: /premium
  cracked:
    description: Disable Premium Auto-Login
    usage: /cracked
  2fa:
    description: Manage Two-Factor Authentication
    usage: /2fa <setup|remove>
  pureauth:
    description: Administrative command for PureAuth
    permission: pureauth.admin
    usage: /pureauth <help|reload|unregister|info|forcelogin|location|stats|register>
permissions:
  pureauth.admin:
    description: Allows access to all PureAuth admin commands
    default: op